ALTER TYPE "ProductionObjectType" ADD VALUE IF NOT EXISTS 'BAR';
ALTER TYPE "ProductionObjectType" ADD VALUE IF NOT EXISTS 'KOLHOZ';
ALTER TYPE "ResourceLogReason" ADD VALUE IF NOT EXISTS 'CYCLE_INPUT';
ALTER TYPE "ResourceLogReason" ADD VALUE IF NOT EXISTS 'CYCLE_OUTPUT';
ALTER TYPE "ResourceLogReason" ADD VALUE IF NOT EXISTS 'OBJECT_STOCK_PUT';
ALTER TYPE "ResourceLogReason" ADD VALUE IF NOT EXISTS 'OBJECT_STOCK_TAKE';
ALTER TYPE "ProductionLogEvent" ADD VALUE IF NOT EXISTS 'CYCLE_STARTED';
ALTER TYPE "ProductionLogEvent" ADD VALUE IF NOT EXISTS 'CYCLE_COMPLETED';
ALTER TYPE "ProductionLogEvent" ADD VALUE IF NOT EXISTS 'CYCLE_FAILED';
CREATE TYPE "ProductionCycleStatus" AS ENUM ('PENDING', 'RUNNING', 'COMPLETED', 'FAILED');
CREATE TYPE "ProductionCycleFailure" AS ENUM ('INPUT_MISSING', 'OUTPUT_FULL', 'EQUIPMENT_BROKEN', 'NEGATIVE_BALANCE', 'OBJECT_DAMAGED', 'PROFILE_SWITCHING', 'LABOR_TIMEOUT');
CREATE TYPE "ResourceQuality" AS ENUM ('POOR', 'NORMAL', 'FINE');
ALTER TABLE "production_objects" ADD COLUMN "storage_capacity" INTEGER NOT NULL DEFAULT 0, ADD COLUMN "active_recipe_id" TEXT;
CREATE TABLE "production_recipes" ("id" TEXT NOT NULL, "code" TEXT NOT NULL, "name" TEXT NOT NULL, "production_object_code" TEXT NOT NULL, "output_resource_code" TEXT, "output_item_template_code" TEXT, "output_amount" INTEGER NOT NULL DEFAULT 1, "cycle_minutes" INTEGER NOT NULL, "labor_required" INTEGER NOT NULL, "required_profession_code" TEXT NOT NULL, "required_profession_level" INTEGER NOT NULL DEFAULT 0, "required_tool_tier" INTEGER NOT NULL DEFAULT 1, "is_active" BOOLEAN NOT NULL DEFAULT true, "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "production_recipes_pkey" PRIMARY KEY ("id"));
CREATE TABLE "production_recipe_inputs" ("id" TEXT NOT NULL, "recipe_id" TEXT NOT NULL, "resource_code" TEXT NOT NULL, "amount" INTEGER NOT NULL, "min_quality" "ResourceQuality" NOT NULL DEFAULT 'POOR', CONSTRAINT "production_recipe_inputs_pkey" PRIMARY KEY ("id"));
CREATE TABLE "production_object_inventory" ("id" TEXT NOT NULL, "production_object_id" TEXT NOT NULL, "resource_code" TEXT NOT NULL, "quality" "ResourceQuality" NOT NULL DEFAULT 'NORMAL', "amount" INTEGER NOT NULL DEFAULT 0, "reserved_amount" INTEGER NOT NULL DEFAULT 0, "updated_at" TIMESTAMP(3) NOT NULL, CONSTRAINT "production_object_inventory_pkey" PRIMARY KEY ("id"));
CREATE TABLE "production_cycles" ("id" TEXT NOT NULL, "production_object_id" TEXT NOT NULL, "recipe_id" TEXT NOT NULL, "status" "ProductionCycleStatus" NOT NULL DEFAULT 'PENDING', "labor_required" INTEGER NOT NULL, "labor_accumulated" INTEGER NOT NULL DEFAULT 0, "started_at" TIMESTAMP(3), "ends_at" TIMESTAMP(3), "completed_at" TIMESTAMP(3), "failure_reason" "ProductionCycleFailure", "output_quality" "ResourceQuality", "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "production_cycles_pkey" PRIMARY KEY ("id"));
CREATE TABLE "cycle_labor_contributions" ("id" TEXT NOT NULL, "cycle_id" TEXT NOT NULL, "character_id" TEXT NOT NULL, "work_shift_id" TEXT NOT NULL, "labor_minutes" INTEGER NOT NULL, "profession_level" INTEGER NOT NULL, "tool_tier" INTEGER NOT NULL DEFAULT 0, "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "cycle_labor_contributions_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "production_recipes_code_key" ON "production_recipes"("code");
CREATE INDEX "production_recipes_production_object_code_idx" ON "production_recipes"("production_object_code");
CREATE UNIQUE INDEX "production_recipe_inputs_recipe_id_resource_code_key" ON "production_recipe_inputs"("recipe_id", "resource_code");
CREATE UNIQUE INDEX "production_object_inventory_production_object_id_resource_code_quality_key" ON "production_object_inventory"("production_object_id", "resource_code", "quality");
CREATE INDEX "production_object_inventory_production_object_id_idx" ON "production_object_inventory"("production_object_id");
CREATE INDEX "production_cycles_production_object_id_status_idx" ON "production_cycles"("production_object_id", "status");
CREATE INDEX "production_cycles_status_ends_at_idx" ON "production_cycles"("status", "ends_at");
CREATE UNIQUE INDEX "cycle_labor_contributions_work_shift_id_key" ON "cycle_labor_contributions"("work_shift_id");
CREATE INDEX "cycle_labor_contributions_cycle_id_idx" ON "cycle_labor_contributions"("cycle_id");
CREATE INDEX "cycle_labor_contributions_character_id_idx" ON "cycle_labor_contributions"("character_id");
ALTER TABLE "production_recipe_inputs" ADD CONSTRAINT "production_recipe_inputs_recipe_id_fkey" FOREIGN KEY ("recipe_id") REFERENCES "production_recipes"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "production_object_inventory" ADD CONSTRAINT "production_object_inventory_production_object_id_fkey" FOREIGN KEY ("production_object_id") REFERENCES "production_objects"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "production_cycles" ADD CONSTRAINT "production_cycles_production_object_id_fkey" FOREIGN KEY ("production_object_id") REFERENCES "production_objects"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "production_cycles" ADD CONSTRAINT "production_cycles_recipe_id_fkey" FOREIGN KEY ("recipe_id") REFERENCES "production_recipes"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "cycle_labor_contributions" ADD CONSTRAINT "cycle_labor_contributions_cycle_id_fkey" FOREIGN KEY ("cycle_id") REFERENCES "production_cycles"("id") ON DELETE CASCADE ON UPDATE CASCADE;
