-- ArmorSlot enum: add LEFT_HAND, RIGHT_HAND, GLOVES
ALTER TYPE "ArmorSlot" ADD VALUE IF NOT EXISTS 'LEFT_HAND';
ALTER TYPE "ArmorSlot" ADD VALUE IF NOT EXISTS 'RIGHT_HAND';
ALTER TYPE "ArmorSlot" ADD VALUE IF NOT EXISTS 'GLOVES';

-- ItemType enum: add SHIELD
ALTER TYPE "ItemType" ADD VALUE IF NOT EXISTS 'SHIELD';
