export enum ErrorCode {
  // Auth
  INVALID_CREDENTIALS    = 'AUTH_001',
  TOKEN_EXPIRED          = 'AUTH_002',
  TOKEN_INVALID          = 'AUTH_003',
  SESSION_REVOKED        = 'AUTH_004',
  UNAUTHORIZED           = 'AUTH_005',
  FORBIDDEN              = 'AUTH_006',

  // User / Character
  USER_NOT_FOUND         = 'USER_001',
  USER_ALREADY_EXISTS    = 'USER_002',
  USER_BANNED            = 'USER_003',
  CHARACTER_NOT_FOUND    = 'CHAR_001',
  CHARACTER_ALREADY_EXISTS = 'CHAR_002',
  CHARACTER_IN_BATTLE    = 'CHAR_003',
  CHARACTER_WORKING      = 'CHAR_004',

  // Items
  ITEM_NOT_FOUND         = 'ITEM_001',
  ITEM_NOT_OWNED         = 'ITEM_002',
  ITEM_BROKEN            = 'ITEM_003',
  ITEM_ALREADY_EQUIPPED  = 'ITEM_004',
  ITEM_NOT_EQUIPPED      = 'ITEM_005',
  ITEM_CANNOT_EQUIP      = 'ITEM_006',
  ITEM_LEVEL_REQ         = 'ITEM_007',
  ITEM_WEIGHT_LIMIT      = 'ITEM_008',

  // Shop
  INSUFFICIENT_FUNDS     = 'SHOP_001',
  ITEM_NOT_AVAILABLE     = 'SHOP_002',
  ITEM_NOT_SELLABLE      = 'SHOP_003',

  // Battle
  BATTLE_NOT_FOUND       = 'BATTLE_001',
  BATTLE_NOT_ACTIVE      = 'BATTLE_002',
  BATTLE_NOT_PARTICIPANT = 'BATTLE_003',
  BATTLE_INVALID_ACTION  = 'BATTLE_004',
  BATTLE_ALREADY_ACTIVE  = 'BATTLE_005',
  BATTLE_ACTION_TAKEN    = 'BATTLE_006',
  BATTLE_NO_WEAPON       = 'BATTLE_007',
  BATTLE_LOCK_FAILED     = 'BATTLE_008',
  BATTLE_ROUND_NOT_OPEN  = 'BATTLE_009',

  // Work
  WORK_OBJECT_NOT_FOUND   = 'WORK_001',
  WORK_LEVEL_REQUIRED     = 'WORK_003',
  WORK_NO_SLOTS           = 'WORK_004',
  WORK_ACTIVE_SHIFT       = 'WORK_005',
  WORK_DAILY_LIMIT        = 'WORK_006',
  WORK_CHARACTER_BUSY     = 'WORK_007',
  WORK_NOT_READY          = 'WORK_009',
  WORK_ALREADY_CLAIMED    = 'WORK_010',

  // Repair
  REPAIR_NOT_NEEDED      = 'REPAIR_001',
  REPAIR_ITEM_NOT_OWNED  = 'REPAIR_002',
  REPAIR_INSUFFICIENT_FUNDS = 'REPAIR_003',

  // General
  VALIDATION_ERROR       = 'GEN_001',
  NOT_FOUND              = 'GEN_002',
  INTERNAL_ERROR         = 'GEN_003',
  RATE_LIMITED           = 'GEN_004',
  CONFLICT               = 'GEN_005',
}
