ALTER TYPE "CurrencyLogReason" ADD VALUE IF NOT EXISTS 'CLAN_CREATE';
ALTER TYPE "CurrencyLogReason" ADD VALUE IF NOT EXISTS 'CLAN_TREASURY_DEPOSIT';
ALTER TYPE "CurrencyLogReason" ADD VALUE IF NOT EXISTS 'CLAN_TREASURY_SPEND';
ALTER TYPE "CurrencyLogReason" ADD VALUE IF NOT EXISTS 'CLAN_MAINTENANCE';
ALTER TYPE "ResourceLogReason" ADD VALUE IF NOT EXISTS 'CLAN_STORAGE_DEPOSIT';
ALTER TYPE "ResourceLogReason" ADD VALUE IF NOT EXISTS 'CLAN_STORAGE_WITHDRAW';
CREATE TYPE "ClanMemberStatus" AS ENUM ('ACTIVE','LEFT','KICKED');
CREATE TYPE "ClanRelationType" AS ENUM ('ALLIANCE','HOSTILITY');
CREATE TYPE "ClanInviteStatus" AS ENUM ('PENDING','ACCEPTED','DECLINED','EXPIRED');
CREATE TABLE "clans" ("id" TEXT NOT NULL,"name" TEXT NOT NULL,"tag" TEXT NOT NULL,"level" INTEGER NOT NULL DEFAULT 0,"treasury" INTEGER NOT NULL DEFAULT 0,"maintenance_debt" INTEGER NOT NULL DEFAULT 0,"is_frozen" BOOLEAN NOT NULL DEFAULT false,"last_charged_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP(3) NOT NULL,CONSTRAINT "clans_pkey" PRIMARY KEY("id"));
CREATE UNIQUE INDEX "clans_name_key" ON "clans"("name"); CREATE UNIQUE INDEX "clans_tag_key" ON "clans"("tag");
CREATE TABLE "clan_roles" ("id" TEXT NOT NULL,"clan_id" TEXT NOT NULL,"code" TEXT NOT NULL,"name" TEXT NOT NULL,"rank" INTEGER NOT NULL,"permissions" JSONB NOT NULL,CONSTRAINT "clan_roles_pkey" PRIMARY KEY("id"));
CREATE UNIQUE INDEX "clan_roles_clan_id_code_key" ON "clan_roles"("clan_id","code");
CREATE TABLE "clan_members" ("id" TEXT NOT NULL,"clan_id" TEXT NOT NULL,"character_id" TEXT NOT NULL,"role_id" TEXT NOT NULL,"status" "ClanMemberStatus" NOT NULL DEFAULT 'ACTIVE',"joined_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"left_at" TIMESTAMP(3),"storage_withdrawn_at" TIMESTAMP(3),"storage_withdrawn" INTEGER NOT NULL DEFAULT 0,"treasury_spent_at" TIMESTAMP(3),"treasury_spent" INTEGER NOT NULL DEFAULT 0,CONSTRAINT "clan_members_pkey" PRIMARY KEY("id"));
CREATE UNIQUE INDEX "clan_members_character_id_key" ON "clan_members"("character_id"); CREATE INDEX "clan_members_clan_id_status_idx" ON "clan_members"("clan_id","status");
CREATE TABLE "clan_invites" ("id" TEXT NOT NULL,"clan_id" TEXT NOT NULL,"character_id" TEXT NOT NULL,"invited_by_id" TEXT NOT NULL,"status" "ClanInviteStatus" NOT NULL DEFAULT 'PENDING',"expires_at" TIMESTAMP(3) NOT NULL,"created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "clan_invites_pkey" PRIMARY KEY("id"));
CREATE UNIQUE INDEX "clan_invites_clan_id_character_id_status_key" ON "clan_invites"("clan_id","character_id","status"); CREATE INDEX "clan_invites_character_id_status_idx" ON "clan_invites"("character_id","status");
CREATE TABLE "clan_storage" ("id" TEXT NOT NULL,"clan_id" TEXT NOT NULL,"resource_code" TEXT NOT NULL,"amount" INTEGER NOT NULL DEFAULT 0,"updated_at" TIMESTAMP(3) NOT NULL,CONSTRAINT "clan_storage_pkey" PRIMARY KEY("id")); CREATE UNIQUE INDEX "clan_storage_clan_id_resource_code_key" ON "clan_storage"("clan_id","resource_code");
CREATE TABLE "clan_treasury_logs" ("id" TEXT NOT NULL,"clan_id" TEXT NOT NULL,"character_id" TEXT,"amount" INTEGER NOT NULL,"balance_after" INTEGER NOT NULL,"reason" TEXT NOT NULL,"created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "clan_treasury_logs_pkey" PRIMARY KEY("id")); CREATE INDEX "clan_treasury_logs_clan_id_created_at_idx" ON "clan_treasury_logs"("clan_id","created_at");
CREATE TABLE "clan_relations" ("id" TEXT NOT NULL,"from_clan_id" TEXT NOT NULL,"to_clan_id" TEXT NOT NULL,"type" "ClanRelationType" NOT NULL,"confirmed" BOOLEAN NOT NULL DEFAULT false,"updated_at" TIMESTAMP(3) NOT NULL,CONSTRAINT "clan_relations_pkey" PRIMARY KEY("id")); CREATE UNIQUE INDEX "clan_relations_from_clan_id_to_clan_id_key" ON "clan_relations"("from_clan_id","to_clan_id");
ALTER TABLE "clan_roles" ADD CONSTRAINT "clan_roles_clan_id_fkey" FOREIGN KEY("clan_id") REFERENCES "clans"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "clan_members" ADD CONSTRAINT "clan_members_clan_id_fkey" FOREIGN KEY("clan_id") REFERENCES "clans"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "clan_members" ADD CONSTRAINT "clan_members_role_id_fkey" FOREIGN KEY("role_id") REFERENCES "clan_roles"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "clan_invites" ADD CONSTRAINT "clan_invites_clan_id_fkey" FOREIGN KEY("clan_id") REFERENCES "clans"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "clan_storage" ADD CONSTRAINT "clan_storage_clan_id_fkey" FOREIGN KEY("clan_id") REFERENCES "clans"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "clan_treasury_logs" ADD CONSTRAINT "clan_treasury_logs_clan_id_fkey" FOREIGN KEY("clan_id") REFERENCES "clans"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "clan_relations" ADD CONSTRAINT "clan_relations_from_clan_id_fkey" FOREIGN KEY("from_clan_id") REFERENCES "clans"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "clan_relations" ADD CONSTRAINT "clan_relations_to_clan_id_fkey" FOREIGN KEY("to_clan_id") REFERENCES "clans"("id") ON DELETE CASCADE ON UPDATE CASCADE;
