import{afterAll,beforeAll,beforeEach,describe,expect,it}from'vitest'
import{cleanDatabase,testPrisma,uid}from'./helpers'
import{MarketService}from'../../modules/market/market.service'
import{runMarketExpire}from'../../workers/market-expire.worker'
async function character(money=5000){const login=uid('market');const user=await testPrisma.user.create({data:{login,email:`${login}@test.local`,passwordHash:'x'}});return testPrisma.character.create({data:{userId:user.id,nickname:login,archetype:'WORKER',hpCurrent:80,hpMax:80,money}})}
async function item(ownerId:string){const t=await testPrisma.itemTemplate.create({data:{code:uid('marketitem'),name:'Market item',type:'ARMOR',armorSlot:'CHEST',armor:10,weight:1,durabilityMax:100,priceBase:500,itemTier:2,sourceType:'PRIVATE'}});return testPrisma.itemInstance.create({data:{templateId:t.id,ownerId,quality:'COMMON',durabilityCurrent:100,durabilityMax:100,weight:1,sourceType:'PRIVATE'}})}
async function resource(ownerId:string,amount=10){const t=await testPrisma.resourceTemplate.create({data:{code:uid('marketres'),name:'Market resource',category:'PRIMARY',tier:1,basePrice:8,weight:.5}});await testPrisma.resourceStack.create({data:{characterId:ownerId,resourceTemplateId:t.id,amount}});return t}
describe('MarketService E4',()=>{beforeAll(()=>testPrisma.$connect());beforeEach(()=>cleanDatabase());afterAll(()=>testPrisma.$disconnect())
 it('creates item listing, charges fee and locks item',async()=>{const seller=await character();const owned=await item(seller.id);const r=await MarketService.createItem(seller.id,owned.id,1000,'market-create-item');expect(r.listing.listingFee).toBe(20);expect((await testPrisma.itemInstance.findUniqueOrThrow({where:{id:owned.id}})).status).toBe('ON_MARKET');expect((await testPrisma.character.findUniqueOrThrow({where:{id:seller.id}})).money).toBe(4980);expect(await testPrisma.currencyLog.count({where:{reasonCode:'MARKET_LISTING_TAX'}})).toBe(1)})
 it('creates resource listing and reserves amount',async()=>{const seller=await character();const res=await resource(seller.id);await MarketService.createResource(seller.id,res.id,4,100,'market-create-resource');expect((await testPrisma.resourceStack.findFirstOrThrow({where:{characterId:seller.id}})).reservedAmount).toBe(4)})
 it('buys item with tax, transfer, eco exp and idempotent replay',async()=>{const seller=await character();const buyer=await character();const owned=await item(seller.id);const created=await MarketService.createItem(seller.id,owned.id,1000,'market-create-buy');const first=await MarketService.buy(buyer.id,created.listing.id,'market-buy-replay');const replay=await MarketService.buy(buyer.id,created.listing.id,'market-buy-replay');expect(first.payout).toBe(950);expect(replay.replayed).toBe(true);expect((await testPrisma.itemInstance.findUniqueOrThrow({where:{id:owned.id}})).ownerId).toBe(buyer.id);expect((await testPrisma.character.findUniqueOrThrow({where:{id:seller.id}})).money).toBe(5930);expect((await testPrisma.character.findUniqueOrThrow({where:{id:buyer.id}})).money).toBe(4000);expect(await testPrisma.currencyLog.count({where:{refId:created.listing.id}})).toBe(3)})
 it('allows exactly one buyer in a race and leaves loser money untouched',async()=>{const seller=await character();const b1=await character();const b2=await character();const owned=await item(seller.id);const listing=(await MarketService.createItem(seller.id,owned.id,1000,'market-race-create')).listing;const results=await Promise.allSettled([MarketService.buy(b1.id,listing.id,'market-race-buy1'),MarketService.buy(b2.id,listing.id,'market-race-buy2')]);expect(results.filter(x=>x.status==='fulfilled')).toHaveLength(1);expect(results.filter(x=>x.status==='rejected')).toHaveLength(1);const transferred=await testPrisma.itemInstance.findUniqueOrThrow({where:{id:owned.id}});const loser=transferred.ownerId===b1.id?b2:b1;expect((await testPrisma.character.findUniqueOrThrow({where:{id:loser.id}})).money).toBe(5000)})
 it('cancels and expires listings, returning item or reservation without fee refund',async()=>{const seller=await character();const owned=await item(seller.id);const a=(await MarketService.createItem(seller.id,owned.id,100,'market-cancel-create')).listing;await MarketService.cancel(seller.id,a.id);expect((await testPrisma.itemInstance.findUniqueOrThrow({where:{id:owned.id}})).status).toBe('NORMAL');expect((await testPrisma.character.findUniqueOrThrow({where:{id:seller.id}})).money).toBe(4995);const res=await resource(seller.id);const b=(await MarketService.createResource(seller.id,res.id,3,100,'market-expire-create')).listing;await testPrisma.marketListing.update({where:{id:b.id},data:{expiresAt:new Date(Date.now()-1000)}});expect(await runMarketExpire()).toBe(1);expect((await testPrisma.resourceStack.findFirstOrThrow({where:{characterId:seller.id,resourceTemplateId:res.id}})).reservedAmount).toBe(0)})
 it('buys a resource listing and moves the reserved stack atomically',async()=>{const seller=await character();const buyer=await character();const res=await resource(seller.id,10);const listing=(await MarketService.createResource(seller.id,res.id,4,100,'market-resource-create')).listing;await MarketService.buy(buyer.id,listing.id,'market-resource-buy');const sellerStack=await testPrisma.resourceStack.findUniqueOrThrow({where:{characterId_resourceTemplateId:{characterId:seller.id,resourceTemplateId:res.id}}});const buyerStack=await testPrisma.resourceStack.findUniqueOrThrow({where:{characterId_resourceTemplateId:{characterId:buyer.id,resourceTemplateId:res.id}}});expect([sellerStack.amount,sellerStack.reservedAmount]).toEqual([6,0]);expect(buyerStack.amount).toBe(4);expect((await testPrisma.marketListing.findUniqueOrThrow({where:{id:listing.id}})).status).toBe('SOLD')})
 it('filters weapon listings by combat range and exact level',async()=>{const seller=await character(10000);const make=async(code:string,weaponType:'KNIFE'|'PISTOL',levelReq:number)=>{const t=await testPrisma.itemTemplate.create({data:{code:uid(code),name:code,type:'WEAPON',weaponType,minDamage:10,maxDamage:20,weight:1,durabilityMax:100,priceBase:500,levelReq,sourceType:'PRIVATE'}});const x=await testPrisma.itemInstance.create({data:{templateId:t.id,ownerId:seller.id,quality:'COMMON',durabilityCurrent:100,durabilityMax:100,weight:1,sourceType:'PRIVATE'}});await MarketService.createItem(seller.id,x.id,100,`filter-${code}`)};await make('knife','KNIFE',1);await make('pistol','PISTOL',2);const melee=await MarketService.list({page:1,limit:20,combat:'MELEE',level:1});const ranged=await MarketService.list({page:1,limit:20,combat:'RANGED',level:2});expect(melee.items).toHaveLength(1);expect(melee.items[0].item?.weaponType).toBe('KNIFE');expect(ranged.items).toHaveLength(1);expect(ranged.items[0].item?.weaponType).toBe('PISTOL')})

 it('blocks self-buy and eleventh active listing',async()=>{const seller=await character(10000);const owned=await item(seller.id);const listing=(await MarketService.createItem(seller.id,owned.id,100,'market-self-create')).listing;await expect(MarketService.buy(seller.id,listing.id,'market-self-buy')).rejects.toMatchObject({statusCode:403});for(let i=1;i<10;i++){const itx=await item(seller.id);await MarketService.createItem(seller.id,itx.id,100,`market-limit-${i}`)}const extra=await item(seller.id);await expect(MarketService.createItem(seller.id,extra.id,100,'market-limit-extra')).rejects.toMatchObject({statusCode:409})})
})
