import{afterAll,beforeAll,beforeEach,describe,expect,it}from'vitest'
import{cleanDatabase,testPrisma,uid}from'./helpers'
import{PrivateShopsService}from'../../modules/private-shops/private-shops.service'
async function fixture(stockMode:'INFINITE'|'LIMITED'='INFINITE',stockAmount:number|null=null,money=1000){const login=uid('ps');const user=await testPrisma.user.create({data:{login,email:`${login}@test.local`,passwordHash:'x'}});const character=await testPrisma.character.create({data:{userId:user.id,nickname:login,archetype:'WORKER',hpCurrent:80,hpMax:80,money}});const template=await testPrisma.itemTemplate.create({data:{code:uid('tier2'),name:'Tier2',type:'ARMOR',armorSlot:'CHEST',armor:16,weight:2,durabilityMax:100,priceBase:900,itemTier:2,sourceType:'PRIVATE',privateShopAllowed:true,upgradeAllowed:true}});const entry=await testPrisma.privateShopItem.create({data:{shopCode:'kommersant',itemTemplateId:template.id,price:900,stockMode,stockAmount}});return{character,template,entry}}
describe('PrivateShopsService',()=>{beforeAll(()=>testPrisma.$connect());beforeEach(()=>cleanDatabase());afterAll(()=>testPrisma.$disconnect())
 it('buys infinite tier2 item atomically and logs it',async()=>{const{character,entry}=await fixture();const r=await PrivateShopsService.buy(character.id,'kommersant',entry.id,1,'private-buy-0001');expect(r.newBalance).toBe(100);const item=await testPrisma.itemInstance.findFirstOrThrow({where:{ownerId:character.id}});expect(item.sourceType).toBe('PRIVATE');expect(await testPrisma.currencyLog.count({where:{reasonCode:'PRIVATE_SHOP_BUY'}})).toBe(1);expect(await testPrisma.itemLog.count({where:{actionCode:'CREATED_FROM_PRIVATE_SHOP'}})).toBe(1)})
 it('decrements limited stock and replays same key once',async()=>{const{character,entry}=await fixture('LIMITED',2,2000);await PrivateShopsService.buy(character.id,'kommersant',entry.id,1,'private-buy-replay');const replay=await PrivateShopsService.buy(character.id,'kommersant',entry.id,1,'private-buy-replay');expect(replay.replayed).toBe(true);expect((await testPrisma.privateShopItem.findUniqueOrThrow({where:{id:entry.id}})).stockAmount).toBe(1);expect(await testPrisma.itemInstance.count({where:{ownerId:character.id}})).toBe(1)})
 it('rejects requirements, no stock and insufficient money without mutation',async()=>{const a=await fixture('LIMITED',0,1000);await expect(PrivateShopsService.buy(a.character.id,'kommersant',a.entry.id,1,'private-buy-stock')).rejects.toMatchObject({statusCode:409});const b=await fixture('INFINITE',null,10);await expect(PrivateShopsService.buy(b.character.id,'kommersant',b.entry.id,1,'private-buy-money')).rejects.toMatchObject({statusCode:400});await testPrisma.privateShopItem.update({where:{id:b.entry.id},data:{minBattleLevel:5}});await expect(PrivateShopsService.buy(b.character.id,'kommersant',b.entry.id,1,'private-buy-level')).rejects.toMatchObject({statusCode:403})})
})
