import{afterAll,beforeAll,beforeEach,describe,expect,it}from'vitest'
import{cleanDatabase,testPrisma,uid}from'./helpers'
import{UpgradesService}from'../../modules/upgrades/upgrades.service'
async function fixture(money=10000,parts=20){const login=uid('upg');const user=await testPrisma.user.create({data:{login,email:`${login}@test.local`,passwordHash:'x'}});const character=await testPrisma.character.create({data:{userId:user.id,nickname:login,archetype:'WORKER',hpCurrent:80,hpMax:80,money,productionLevel:0}});const resource=await testPrisma.resourceTemplate.upsert({where:{code:'comp_weapon_part'},update:{},create:{code:'comp_weapon_part',name:'Weapon part',category:'UPGRADE_PART',tier:2,basePrice:60,weight:.5,isUpgradeMaterial:true}});await testPrisma.resourceStack.create({data:{characterId:character.id,resourceTemplateId:resource.id,amount:parts}});const template=await testPrisma.itemTemplate.create({data:{code:uid('upgitem'),name:'TT',type:'WEAPON',weaponType:'PISTOL',minDamage:45,maxDamage:90,weaponAccuracy:.78,weight:1,durabilityMax:100,priceBase:2400,itemTier:2,sourceType:'PRIVATE',upgradeAllowed:true}});const item=await testPrisma.itemInstance.create({data:{templateId:template.id,ownerId:character.id,quality:'COMMON',durabilityCurrent:80,durabilityMax:100,weight:1,sourceType:'PRIVATE'}});return{character,item,resource}}
describe('UpgradesService E5',()=>{beforeAll(()=>testPrisma.$connect());beforeEach(()=>cleanDatabase());afterAll(()=>testPrisma.$disconnect())
 it('preview changes nothing and returns cost, chance and resources',async()=>{const{character,item}=await fixture();const p=await UpgradesService.preview(character.id,item.id,'DAMAGE');expect(p.cost).toBe(360);expect(p.chance).toBe(.9);expect(p.requiredResources[0]).toMatchObject({amount:1,available:20,enough:true});expect((await testPrisma.itemInstance.findUniqueOrThrow({where:{id:item.id}})).upgradeLevel).toBe(0)})
 it('commits success and replays same key without a second charge',async()=>{const{character,item}=await fixture();const first=await UpgradesService.commit(character.id,item.id,'DAMAGE','upgrade-success-key',()=>0);const replay=await UpgradesService.commit(character.id,item.id,'DAMAGE','upgrade-success-key',()=>0);expect(first.success).toBe(true);expect(replay.replayed).toBe(true);const saved=await testPrisma.itemInstance.findUniqueOrThrow({where:{id:item.id}});expect(saved.upgradeLevel).toBe(1);expect(saved.upgradeModifiersJson).toEqual({DAMAGE:1});expect((await testPrisma.character.findUniqueOrThrow({where:{id:character.id}})).money).toBe(9640);expect((await testPrisma.resourceStack.findFirstOrThrow({where:{characterId:character.id}})).amount).toBe(19);expect(await testPrisma.upgradeLog.count()).toBe(1)})
 it('failure burns money and parts but leaves item unchanged',async()=>{const{character,item}=await fixture();const r=await UpgradesService.commit(character.id,item.id,'DAMAGE','upgrade-fail-key',()=>.99);expect(r.success).toBe(false);expect((await testPrisma.itemInstance.findUniqueOrThrow({where:{id:item.id}})).upgradeLevel).toBe(0);expect((await testPrisma.character.findUniqueOrThrow({where:{id:character.id}})).money).toBe(9640);expect((await testPrisma.resourceStack.findFirstOrThrow({where:{characterId:character.id}})).amount).toBe(19);expect((await testPrisma.upgradeLog.findFirstOrThrow()).resultCode).toBe('FAIL')})
 it('rejects missing resources, foreign item, market item and max level without charging',async()=>{const a=await fixture(10000,0);await expect(UpgradesService.commit(a.character.id,a.item.id,'DAMAGE','upgrade-no-parts',()=>0)).rejects.toMatchObject({statusCode:409});const other=await fixture();await expect(UpgradesService.commit(other.character.id,a.item.id,'DAMAGE','upgrade-foreign',()=>0)).rejects.toMatchObject({statusCode:403});await testPrisma.itemInstance.update({where:{id:a.item.id},data:{status:'ON_MARKET'}});await expect(UpgradesService.commit(a.character.id,a.item.id,'DAMAGE','upgrade-market',()=>0)).rejects.toMatchObject({statusCode:409});await testPrisma.itemInstance.update({where:{id:a.item.id},data:{status:'NORMAL',upgradeLevel:5}});await expect(UpgradesService.commit(a.character.id,a.item.id,'DAMAGE','upgrade-maxxx',()=>0)).rejects.toMatchObject({statusCode:400});expect((await testPrisma.character.findUniqueOrThrow({where:{id:a.character.id}})).money).toBe(10000)})
})
