ALTER TYPE "CurrencyLogReason" ADD VALUE IF NOT EXISTS 'OBJECT_PURCHASE';
ALTER TYPE "CurrencyLogReason" ADD VALUE IF NOT EXISTS 'OBJECT_SALE';
ALTER TYPE "CurrencyLogReason" ADD VALUE IF NOT EXISTS 'OBJECT_BALANCE_TOP_UP';
ALTER TYPE "CurrencyLogReason" ADD VALUE IF NOT EXISTS 'OBJECT_WITHDRAW';
ALTER TYPE "CurrencyLogReason" ADD VALUE IF NOT EXISTS 'OBJECT_WITHDRAW_TAX';
ALTER TYPE "CurrencyLogReason" ADD VALUE IF NOT EXISTS 'SALARY_FROM_OBJECT';
ALTER TYPE "ProductionLogEvent" ADD VALUE IF NOT EXISTS 'OBJECT_OWNERSHIP_CHANGED';
ALTER TYPE "ProductionLogEvent" ADD VALUE IF NOT EXISTS 'OBJECT_BALANCE_CHANGED';
ALTER TABLE "production_objects"
  ADD COLUMN "purchase_price" INTEGER,
  ADD COLUMN "is_for_sale" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN "salary_override" INTEGER,
  ADD COLUMN "maintenance_debt" INTEGER NOT NULL DEFAULT 0;
