import { readFileSync, writeFileSync } from 'node:fs'
import { resolveZonalAttack, type AttackerSnapshot, type DefenderSnapshot } from '../backend/src/modules/battles/battle.formulas'

type Row = { id:string; phase:string; group:string; hypothesis:string; attacker:string; defender:string; stance_b:string; runs:string; acceptance_or_decision_rule:string }
function csv(line:string){const out:string[]=[];let x='',q=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'){if(q&&line[i+1]==='"'){x+='"';i++}else q=!q}else if(c===','&&!q){out.push(x);x=''}else x+=c}out.push(x);return out}
const raw=readFileSync(new URL('../docs/research/data/apeha_combat_experiment_matrix.csv',import.meta.url),'utf8').replace(/^\uFEFF/,'').trim().split(/\r?\n/).filter(Boolean)
const head=csv(raw.shift()!);const rows=raw.map(line=>{const values=csv(line);return Object.fromEntries(head.map((h,i)=>[h,values[i]??''])) as Row})
function seed(text:string){let s=2166136261;for(const c of text)s=Math.imul(s^c.charCodeAt(0),16777619);return()=>((s=Math.imul(s^s>>>15,2246822519))>>>0)/4294967296}
function attack(desc:string):AttackerSnapshot{const d=desc.toLowerCase();return{str:d.includes('strength')||d.includes('strong')?14:7,acc:d.includes('accuracy')?16:8,agi:d.includes('dodge')?15:7,rea:d.includes('reaction')?15:7,luck:d.includes('luck')?16:5,agr:d.includes('crit')||d.includes('anger')?16:6,end:7,weaponSkillLevel:8,minDamage:18,maxDamage:32,weaponAccuracy:.78,critBonus:d.includes('crit')?.08:0,critDamageBonus:0,blockPierce:0,flatDamageBonus:0,equipmentWeight:4,antiDodgeBonus:d.includes('accuracy')?.12:0,antiCounterBonus:d.includes('anti-counter')?.12:0}}
function defend(desc:string):DefenderSnapshot{const d=desc.toLowerCase();return{agi:d.includes('dodge')?16:7,rea:d.includes('reaction')||d.includes('block')?15:7,end:d.includes('tank')||d.includes('armor')?15:7,luck:5,armor:d.includes('armor')||d.includes('tank')?35:12,dodgeBonus:0,antiCrit:d.includes('anti-crit')?.14:0,blockBonus:d.includes('block')?.15:0,armorWeight:d.includes('armor')||d.includes('tank')?12:4,antiSkillLevel:0,antiCounterDefense:0,antiLuck:d.includes('block')?.12:0,minDamage:12,maxDamage:22}}
function blocks(stance:string){return stance==='defense4'?['HEAD','CHEST','LEGS','RIGHT_ARM'] as const:stance==='mixed'?['HEAD','CHEST'] as const:[] as const}
const results=rows.map(row=>{const rng=seed(row.id),a=attack(row.attacker),d=defend(row.defender),n=Math.min(1000,Math.max(100,Number(row.runs)||100));let hit=0,dodge=0,block=0,crit=0,pierce=0,counter=0,damage=0;for(let i=0;i<n;i++){const zone=(['HEAD','CHEST','LEGS','RIGHT_ARM','LEFT_ARM'] as const)[i%5];const r=resolveZonalAttack(a,d,{zone,blockedZones:[...blocks(row.stance_b)],zoneArmor:d.armor,rng});hit+=+r.hit;dodge+=+r.dodge;block+=+r.block;crit+=+r.crit;pierce+=+r.blockPierced;counter+=+(r.counterDamage>0);damage+=r.finalDamage}const rates={hit:hit/n,dodge:dodge/n,block:block/n,crit:crit/n,pierce:pierce/n,counter:counter/n,damagePerAttack:damage/n};const valid=Object.values(rates).every(Number.isFinite)&&Object.entries(rates).filter(([k])=>k!=='damagePerAttack').every(([,v])=>v>=0&&v<=1)&&rates.damagePerAttack>=0;return{id:row.id,phase:Number(row.phase),group:row.group,hypothesis:row.hypothesis,runs:n,rates,valid,rule:row.acceptance_or_decision_rule}})
const report={generatedAt:new Date().toISOString(),sourceRows:rows.length,canonicalDecisions:{resolution:'single accuracy/evasion contest before block',lucky:'pierces block only; armor still applies',counter:'bounded fraction of incoming force',wards:['anti-dodge','anti-luck','anti-counter','anti-crit']},valid:results.every(x=>x.valid)&&results.length===40,results}
const jsonArg=process.argv.indexOf('--json'),textArg=process.argv.indexOf('--text');if(jsonArg>=0)writeFileSync(process.argv[jsonArg+1],JSON.stringify(report,null,2)+'\n');const text=[`APEHA COMBAT MATRIX: ${report.valid?'PASS':'FAIL'}`,`Experiments executed: ${results.length}/40`,...results.map(x=>`${x.id} ${x.valid?'PASS':'FAIL'} hit=${x.rates.hit.toFixed(3)} dodge=${x.rates.dodge.toFixed(3)} block=${x.rates.block.toFixed(3)} crit=${x.rates.crit.toFixed(3)} pierce=${x.rates.pierce.toFixed(3)} counter=${x.rates.counter.toFixed(3)} dmg=${x.rates.damagePerAttack.toFixed(2)}`)].join('\n')+'\n';if(textArg>=0)writeFileSync(process.argv[textArg+1],text);console.log(text);process.exit(report.valid?0:1)
