import { useMemo, useState } from 'react'
import './balance-sandbox.css'

type Profile='fighter'|'worker'|'mixed'
const profiles:Record<Profile,{battles:number;shifts:number;marketEvery:number}>={fighter:{battles:15,shifts:0,marketEvery:4},worker:{battles:1,shifts:8,marketEvery:3},mixed:{battles:6,shifts:4,marketEvery:3}}
const labels:Record<Profile,string>={fighter:'Боец',worker:'Рабочий',mixed:'Смешанный'}
function run(days:number,players:number,salary:number,battleReward:number,repair:number,tax:number){return (Object.keys(profiles) as Profile[]).map(key=>{const p=profiles[key];let money=1250, minted=0,burned=0;for(let d=1;d<=days;d++){const battle=p.battles*battleReward*.6;let work=0;for(let s=1;s<=p.shifts;s++)work+=salary*Math.max(.2,1-(s-1)*.2);const market=d%p.marketEvery===0?160:0;const income=battle+work+market;const sinks=p.battles*1.8+(d%5===0?150:0)+(d%p.marketEvery===0?Math.max(5,160*.02)+160*tax:0)+(d%10===5?repair:0);minted+=income;burned+=sinks;money=Math.max(0,money+income-sinks)}return{key,money:Math.round(money),daily:Math.round((minted-burned)/days),minted:Math.round(minted*players/3),burned:Math.round(burned*players/3),sink:burned/Math.max(1,minted)}})}
export function BalanceSandboxPage(){const[days,setDays]=useState(30),[players,setPlayers]=useState(300),[salary,setSalary]=useState(100),[battle,setBattle]=useState(55),[repair,setRepair]=useState(200),[tax,setTax]=useState(.05);const rows=useMemo(()=>run(days,players,salary,battle,repair,tax),[days,players,salary,battle,repair,tax]);const max=Math.max(...rows.map(x=>x.money));const exportJson=()=>{const blob=new Blob([JSON.stringify({inputs:{days,players,salary,battleReward:battle,repair,tax},rows},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='balance-sandbox.json';a.click();URL.revokeObjectURL(a.href)};return <main className="balance-sandbox"><header><div><span className="sandbox-kicker">ТЕХНИЧЕСКАЯ ПЕСОЧНИЦА</span><h1>Баланс экономики</h1><p>Быстрый стенд для сравнения профилей. Коэффициенты повторяют Stage 2 и ориентиры GanjaWars / Apeha.</p></div><button className="sandbox-export" onClick={exportJson}>Скачать JSON</button></header><section className="sandbox-controls" aria-label="Параметры симуляции"><Control label="Дней" value={days} min={8} max={180} set={setDays}/><Control label="Игроков" value={players} min={30} max={3000} step={30} set={setPlayers}/><Control label="Базовая зарплата" value={salary} min={40} max={300} set={setSalary}/><Control label="Награда за бой" value={battle} min={10} max={150} set={setBattle}/><Control label="Ремонт" value={repair} min={50} max={800} step={10} set={setRepair}/><Control label="Налог рынка, %" value={Math.round(tax*100)} min={0} max={20} set={v=>setTax(v/100)}/></section><section className="sandbox-results"><div className="sandbox-ruler"><span>Старт 1 250 ₽</span><span>Капитал после {days} дней</span></div>{rows.map(r=><article key={r.key}><div className="sandbox-profile"><strong>{labels[r.key]}</strong><small>{profiles[r.key].battles} боёв · {profiles[r.key].shifts} смен/день</small></div><div className="sandbox-bar"><i style={{width:`${Math.max(3,r.money/max*100)}%`}}/></div><b>{r.money.toLocaleString('ru')} ₽</b><span className={r.daily>=0?'positive':'negative'}>{r.daily>=0?'+':''}{r.daily} ₽/день</span><span>стоки {Math.round(r.sink*100)}%</span></article>)}</section><footer><b>Красные флаги:</b> профиль уходит в минус, разрыв дохода выше 35%, стоки ниже 45% или выше 80%. Меняй один параметр за раз.</footer></main>}
function Control({label,value,min,max,step=1,set}:{label:string;value:number;min:number;max:number;step?:number;set:(v:number)=>void}){return <label><span>{label}</span><output>{value}</output><input type="range" value={value} min={min} max={max} step={step} onChange={e=>set(Number(e.target.value))}/></label>}
