import{prisma}from'../../shared/db/prisma'
import{withIdempotency}from'../../shared/db/idempotency'
import{withTransaction}from'../../shared/db/transaction'
import{AppError}from'../../shared/errors/app-error'
import{ErrorCode}from'../../shared/errors/error-codes'
import{EconomyService}from'../economy/economy.service'
import{ResourcesService}from'../resources/resources.service'
import{calcListingFee,calcMarketSellerEcoExp,calcSaleTax,calcSellerPayout,marketListingExpiresAt}from'./market.formulas'
export const MarketService={
 async list(params:{page:number;limit:number;type?:'ITEM'|'RESOURCE';sellerCharacterId?:string}){const where={status:'ACTIVE' as const,...(params.type?{type:params.type}:{}),...(params.sellerCharacterId?{sellerCharacterId:params.sellerCharacterId}:{})};const[items,total]=await Promise.all([prisma.marketListing.findMany({where,orderBy:{createdAt:'desc'},skip:(params.page-1)*params.limit,take:params.limit}),prisma.marketListing.count({where})]);const sellers=await prisma.character.findMany({where:{id:{in:[...new Set(items.map(x=>x.sellerCharacterId))]}},select:{id:true,nickname:true}});const names=new Map(sellers.map(x=>[x.id,x.nickname]));return{items:items.map(x=>({...x,sellerNickname:names.get(x.sellerCharacterId),sellerUrl:`/u/${names.get(x.sellerCharacterId)}`})),total,page:params.page,limit:params.limit,totalPages:Math.ceil(total/params.limit)}},
 async createItem(characterId:string,itemInstanceId:string,price:number,key:string){return withIdempotency({characterId,scope:'market.listings.create',key,execute:async tx=>{if(await tx.marketListing.count({where:{sellerCharacterId:characterId,status:{in:['ACTIVE','LOCKED']}}})>=10)throw new AppError(ErrorCode.MARKET_LIMIT,'Maximum 10 active listings',409);const item=await tx.itemInstance.findUnique({where:{id:itemInstanceId},include:{template:true}});if(!item||item.ownerId!==characterId)throw new AppError(ErrorCode.ITEM_NOT_OWNED,'Not your item',403);if(item.isEquipped||item.status!=='NORMAL'||!item.template.isTradeable)throw new AppError(ErrorCode.MARKET_ITEM_INVALID,'Item cannot be listed',409);const fee=calcListingFee(price);const newBalance=await EconomyService.debit(tx,{characterId,amount:fee,reasonCode:'MARKET_LISTING_TAX',refType:'market_listing'});const listing=await tx.marketListing.create({data:{sellerCharacterId:characterId,type:'ITEM',itemInstanceId,price,listingFee:fee,expiresAt:marketListingExpiresAt()}});await tx.itemInstance.update({where:{id:item.id},data:{status:'ON_MARKET'}});await tx.itemLog.create({data:{itemId:item.id,characterId,actionCode:'LISTED_ON_MARKET',details:{listingId:listing.id,price,fee}}});return{listing,newBalance}}})},
 async createResource(characterId:string,resourceTemplateId:string,amount:number,price:number,key:string){return withIdempotency({characterId,scope:'market.listings.create',key,execute:async tx=>{if(await tx.marketListing.count({where:{sellerCharacterId:characterId,status:{in:['ACTIVE','LOCKED']}}})>=10)throw new AppError(ErrorCode.MARKET_LIMIT,'Maximum 10 active listings',409);const resource=await tx.resourceTemplate.findUnique({where:{id:resourceTemplateId}});if(!resource?.isTradable||!resource.isActive)throw new AppError(ErrorCode.MARKET_RESOURCE_INVALID,'Resource cannot be listed',409);await ResourcesService.reserve(tx,characterId,resourceTemplateId,amount);const fee=calcListingFee(price);const newBalance=await EconomyService.debit(tx,{characterId,amount:fee,reasonCode:'MARKET_LISTING_TAX',refType:'market_listing'});const listing=await tx.marketListing.create({data:{sellerCharacterId:characterId,type:'RESOURCE',resourceTemplateId,resourceAmount:amount,price,listingFee:fee,expiresAt:marketListingExpiresAt()}});await tx.resourceLog.create({data:{characterId,resourceTemplateId,amountDelta:0,balanceAfter:(await tx.resourceStack.findUniqueOrThrow({where:{characterId_resourceTemplateId:{characterId,resourceTemplateId}}})).amount,reasonCode:'MARKET_LIST',refType:'market_listing',refId:listing.id}});return{listing,newBalance}}})},
 async buy(buyerId:string,listingId:string,key:string){return withIdempotency({characterId:buyerId,scope:'market.listings.buy',key,execute:async tx=>{const listing=await tx.marketListing.findUnique({where:{id:listingId}});if(!listing||listing.status!=='ACTIVE')throw new AppError(ErrorCode.MARKET_UNAVAILABLE,'Listing is unavailable',409);if(listing.sellerCharacterId===buyerId)throw new AppError(ErrorCode.MARKET_OWN_LISTING,'Cannot buy own listing',403);const claimed=await tx.marketListing.updateMany({where:{id:listingId,status:'ACTIVE'},data:{status:'SOLD',buyerCharacterId:buyerId,soldAt:new Date(),saleTax:calcSaleTax(listing.price)}});if(claimed.count!==1)throw new AppError(ErrorCode.MARKET_ALREADY_PROCESSED,'Listing already processed',409);const buyerBalance=await EconomyService.debit(tx,{characterId:buyerId,amount:listing.price,reasonCode:'MARKET_BUY',refType:'market_listing',refId:listing.id});const payout=calcSellerPayout(listing.price);await EconomyService.credit(tx,{characterId:listing.sellerCharacterId,amount:listing.price,reasonCode:'MARKET_SELL',refType:'market_listing',refId:listing.id});await EconomyService.debit(tx,{characterId:listing.sellerCharacterId,amount:calcSaleTax(listing.price),reasonCode:'MARKET_SELL_TAX',refType:'market_listing',refId:listing.id});await EconomyService.grantEconomicExp(tx,listing.sellerCharacterId,calcMarketSellerEcoExp(listing.price));if(listing.type==='ITEM'&&listing.itemInstanceId){await tx.itemInstance.update({where:{id:listing.itemInstanceId},data:{ownerId:buyerId,status:'NORMAL',isEquipped:false}});await tx.itemLog.create({data:{itemId:listing.itemInstanceId,characterId:listing.sellerCharacterId,actionCode:'MARKET_SOLD',details:{listingId,buyerId}}});await tx.itemLog.create({data:{itemId:listing.itemInstanceId,characterId:buyerId,actionCode:'MARKET_BOUGHT',details:{listingId,sellerCharacterId:listing.sellerCharacterId}}})}else if(listing.resourceTemplateId&&listing.resourceAmount){await ResourcesService.release(tx,listing.sellerCharacterId,listing.resourceTemplateId,listing.resourceAmount);await ResourcesService.consume(tx,{characterId:listing.sellerCharacterId,resourceTemplateId:listing.resourceTemplateId,amount:listing.resourceAmount,reasonCode:'MARKET_SELL',refType:'market_listing',refId:listing.id});await ResourcesService.add(tx,{characterId:buyerId,resourceTemplateId:listing.resourceTemplateId,amount:listing.resourceAmount,reasonCode:'MARKET_BUY',refType:'market_listing',refId:listing.id})}return{listingId,status:'SOLD',buyerBalance,payout}}})},
 async cancel(characterId:string,listingId:string){return withTransaction(async tx=>{const listing=await tx.marketListing.findUnique({where:{id:listingId}});if(!listing||listing.sellerCharacterId!==characterId)throw new AppError(ErrorCode.MARKET_NOT_OWNER,'Listing not found',404);const changed=await tx.marketListing.updateMany({where:{id:listingId,sellerCharacterId:characterId,status:'ACTIVE'},data:{status:'CANCELLED'}});if(changed.count!==1)throw new AppError(ErrorCode.MARKET_ALREADY_PROCESSED,'Listing cannot be cancelled',409);if(listing.itemInstanceId){await tx.itemInstance.updateMany({where:{id:listing.itemInstanceId,status:'ON_MARKET'},data:{status:'NORMAL'}});await tx.itemLog.create({data:{itemId:listing.itemInstanceId,characterId,actionCode:'MARKET_LISTING_CANCELLED',details:{listingId,reason:'CANCELLED_BY_OWNER'}}})}if(listing.resourceTemplateId&&listing.resourceAmount){const stack=await ResourcesService.release(tx,characterId,listing.resourceTemplateId,listing.resourceAmount);await tx.resourceLog.create({data:{characterId,resourceTemplateId:listing.resourceTemplateId,amountDelta:0,balanceAfter:stack.amount,reasonCode:'MARKET_LIST',refType:'market_listing',refId:listingId}})}return{listingId,status:'CANCELLED'}})}
}
