-- Reconcile Stage 2 PostgreSQL enums on long-lived environments.
-- Every statement is additive and idempotent so existing values and rows are preserved.

ALTER TYPE "WorkShiftStatus" ADD VALUE IF NOT EXISTS 'ACTIVE';
ALTER TYPE "WorkShiftStatus" ADD VALUE IF NOT EXISTS 'READY_TO_CLAIM';
ALTER TYPE "WorkShiftStatus" ADD VALUE IF NOT EXISTS 'CLAIMED';
ALTER TYPE "WorkShiftStatus" ADD VALUE IF NOT EXISTS 'CANCELLED';
ALTER TYPE "WorkShiftStatus" ADD VALUE IF NOT EXISTS 'FAILED';

ALTER TYPE "MarketListingStatus" ADD VALUE IF NOT EXISTS 'ACTIVE';
ALTER TYPE "MarketListingStatus" ADD VALUE IF NOT EXISTS 'LOCKED';
ALTER TYPE "MarketListingStatus" ADD VALUE IF NOT EXISTS 'SOLD';
ALTER TYPE "MarketListingStatus" ADD VALUE IF NOT EXISTS 'CANCELLED';
ALTER TYPE "MarketListingStatus" ADD VALUE IF NOT EXISTS 'EXPIRED';

ALTER TYPE "ProductionLogEvent" ADD VALUE IF NOT EXISTS 'SHIFT_STARTED';
ALTER TYPE "ProductionLogEvent" ADD VALUE IF NOT EXISTS 'SHIFT_READY';
ALTER TYPE "ProductionLogEvent" ADD VALUE IF NOT EXISTS 'SHIFT_CLAIMED';
ALTER TYPE "ProductionLogEvent" ADD VALUE IF NOT EXISTS 'SHIFT_CANCELLED';
ALTER TYPE "ProductionLogEvent" ADD VALUE IF NOT EXISTS 'SHIFT_FAILED';

ALTER TYPE "ResourceLogReason" ADD VALUE IF NOT EXISTS 'WORK_REWARD';
ALTER TYPE "ResourceLogReason" ADD VALUE IF NOT EXISTS 'GOVERNMENT_SELL';
ALTER TYPE "ResourceLogReason" ADD VALUE IF NOT EXISTS 'MARKET_LIST';
ALTER TYPE "ResourceLogReason" ADD VALUE IF NOT EXISTS 'MARKET_BUY';
ALTER TYPE "ResourceLogReason" ADD VALUE IF NOT EXISTS 'MARKET_SELL';
ALTER TYPE "ResourceLogReason" ADD VALUE IF NOT EXISTS 'REPAIR_USE';
ALTER TYPE "ResourceLogReason" ADD VALUE IF NOT EXISTS 'UPGRADE_USE';
ALTER TYPE "ResourceLogReason" ADD VALUE IF NOT EXISTS 'ADMIN_ADJUSTMENT';
ALTER TYPE "ResourceLogReason" ADD VALUE IF NOT EXISTS 'PRIVATE_SHOP_BUY';

ALTER TYPE "CurrencyLogReason" ADD VALUE IF NOT EXISTS 'MARKET_BUY';
ALTER TYPE "CurrencyLogReason" ADD VALUE IF NOT EXISTS 'MARKET_LISTING_TAX';
ALTER TYPE "CurrencyLogReason" ADD VALUE IF NOT EXISTS 'MARKET_SELL_TAX';
ALTER TYPE "CurrencyLogReason" ADD VALUE IF NOT EXISTS 'PRIVATE_SHOP_BUY';
ALTER TYPE "CurrencyLogReason" ADD VALUE IF NOT EXISTS 'RESOURCE_SELL';
ALTER TYPE "CurrencyLogReason" ADD VALUE IF NOT EXISTS 'UPGRADE_COST';
ALTER TYPE "CurrencyLogReason" ADD VALUE IF NOT EXISTS 'ADMIN_ECONOMY_ADJUSTMENT';
ALTER TYPE "CurrencyLogReason" ADD VALUE IF NOT EXISTS 'WORK_SALARY';
