import{afterAll,beforeAll,describe,expect,it}from'vitest'
import{testPrisma,uid}from'./helpers'
const BASE=process.env.E2E_API_URL??'http://127.0.0.1:4400'
async function api(method:string,path:string,body?:unknown,token?:string,idem?:string){const headers:Record<string,string>={};if(body!==undefined)headers['Content-Type']='application/json';if(token)headers.Authorization=`Bearer ${token}`;if(idem)headers['Idempotency-Key']=idem;const res=await fetch(BASE+path,{method,headers,body:body===undefined?undefined:JSON.stringify(body)});return{status:res.status,data:await res.json().catch(()=>null)}}
async function player(prefix:string){const login=uid(prefix);await api('POST','/api/auth/register',{login,email:`${login}@e2e.local`,password:'pass1234'});const logged=await api('POST','/api/auth/login',{login,password:'pass1234'});const token=(logged.data as{token:string}).token;await api('POST','/api/characters',{nickname:uid('Hero'),archetype:'WORKER'},token);const profile=await api('GET','/api/characters/me',undefined,token);return{token,char:profile.data as{id:string}}}
describe('E2E stage2 economy cycle',()=>{let seller:{token:string;char:{id:string}};let buyer:{token:string;char:{id:string}};let itemId='';let resourceId='';beforeAll(async()=>{await testPrisma.$connect();seller=await player('ecoSeller');buyer=await player('ecoBuyer');await testPrisma.character.updateMany({where:{id:{in:[seller.char.id,buyer.char.id]}},data:{money:10000}});const part=await testPrisma.resourceTemplate.findUniqueOrThrow({where:{code:'comp_weapon_part'}});resourceId=part.id;await testPrisma.resourceStack.upsert({where:{characterId_resourceTemplateId:{characterId:seller.char.id,resourceTemplateId:part.id}},update:{amount:20},create:{characterId:seller.char.id,resourceTemplateId:part.id,amount:20}});const template=await testPrisma.itemTemplate.findUniqueOrThrow({where:{code:'weapon_tt_private'}});const item=await testPrisma.itemInstance.create({data:{templateId:template.id,ownerId:seller.char.id,quality:'COMMON',durabilityCurrent:100,durabilityMax:100,weight:template.weight,sourceType:'PRIVATE'}});itemId=item.id});afterAll(()=>testPrisma.$disconnect())
 it('exposes production objects through the specified list and detail API',async()=>{const list=await api('GET','/api/production/objects',undefined,seller.token);expect(list.status).toBe(200);const items=(list.data as{items:Array<{id:string;requiredProfessionCode:string}>}).items;expect(items.length).toBeGreaterThanOrEqual(6);expect(items.every(x=>typeof x.requiredProfessionCode==='string')).toBe(true);const detail=await api('GET',`/api/production/objects/${items[0].id}`,undefined,seller.token);expect(detail.status).toBe(200);expect((detail.data as{id:string}).id).toBe(items[0].id)})

 it('requires, buys and consumes one tool use through the work API',async()=>{const work=await api('GET','/api/work/objects',undefined,seller.token);expect(work.status).toBe(200);const objects=(work.data as{items:Array<{id:string;equipment:{requiredToolTier:number}|null;toolAvailable:boolean}>}).items;const object=objects.find(item=>item.equipment?.requiredToolTier===1);expect(object).toBeTruthy();expect(object!.toolAvailable).toBe(false);const blocked=await api('POST','/api/work/shifts/start',{productionObjectId:object!.id},seller.token);expect(blocked.status).toBe(400);expect((blocked.data as{code:string}).code).toBe('WORK_011');const shop=await api('GET','/api/shops/government/items',undefined,seller.token);expect(shop.status).toBe(200);const tool=(shop.data as Array<{templateId:string;template:{type:string;toolTier:number|null;usesMax:number|null}}>).find(item=>item.template.type==='TOOL'&&item.template.toolTier===1);expect(tool).toBeTruthy();const bought=await api('POST','/api/shops/government/buy',{templateId:tool!.templateId},seller.token);expect(bought.status).toBe(201);expect((bought.data as{item:{usesLeft:number}}).item.usesLeft).toBe(tool!.template.usesMax);const started=await api('POST','/api/work/shifts/start',{productionObjectId:object!.id},seller.token);expect(started.status).toBe(201);const shiftId=(started.data as{shift:{id:string}}).shift.id;await testPrisma.workShift.update({where:{id:shiftId},data:{endsAt:new Date(Date.now()-1000)}});const claimed=await api('POST',`/api/work/shifts/${shiftId}/claim`,undefined,seller.token,'e2e-tool-work-claim');expect(claimed.status).toBe(200);expect((claimed.data as{toolUse:{usesLeft:number}}).toolUse.usesLeft).toBe((tool!.template.usesMax??0)-1);const replay=await api('POST',`/api/work/shifts/${shiftId}/claim`,undefined,seller.token,'e2e-tool-work-claim');expect((replay.data as{replayed:boolean}).replayed).toBe(true)})

 it('sells resources to government idempotently',async()=>{const first=await api('POST','/api/resources/sell',{resourceCode:'comp_weapon_part',amount:1},seller.token,'e2e-resource-sale');const replay=await api('POST','/api/resources/sell',{resourceCode:'comp_weapon_part',amount:1},seller.token,'e2e-resource-sale');expect(first.status).toBe(200);expect((replay.data as{replayed:boolean}).replayed).toBe(true)})
 it('lists item and transfers it through market',async()=>{const created=await api('POST','/api/market/listings',{listingType:'ITEM',itemInstanceId:itemId,price:1000},seller.token,'e2e-market-create');expect(created.status).toBe(201);const listing=(created.data as{listing:{id:string}}).listing;const bought=await api('POST',`/api/market/listings/${listing.id}/buy`,undefined,buyer.token,'e2e-market-buy');expect(bought.status).toBe(200);expect((await testPrisma.itemInstance.findUniqueOrThrow({where:{id:itemId}})).ownerId).toBe(buyer.char.id)})
 it('upgrades purchased item with preview and commit',async()=>{const part=await testPrisma.resourceTemplate.findUniqueOrThrow({where:{id:resourceId}});await testPrisma.resourceStack.upsert({where:{characterId_resourceTemplateId:{characterId:buyer.char.id,resourceTemplateId:part.id}},update:{amount:10},create:{characterId:buyer.char.id,resourceTemplateId:part.id,amount:10}});const preview=await api('POST','/api/upgrades/preview',{itemInstanceId:itemId,upgradeType:'DAMAGE'},buyer.token);expect(preview.status).toBe(200);const commit=await api('POST','/api/upgrades/commit',{itemInstanceId:itemId,upgradeType:'DAMAGE'},buyer.token,'e2e-upgrade-commit');expect(commit.status).toBe(200);expect((commit.data as{levelAfter:number}).levelAfter).toBeGreaterThanOrEqual(0)})
})
